// Sampled from the published Allflame catalog. Hardcoded on purpose.
const CATEGORIES = [
  {
    name: "Currency", key: "Currency",
    palette: {"primary":"#f05a23","secondary":"#ffffff","icon":"Star"}, // you
    hints: [], // from the taxonomy
    tiers: [
      {"name":"T0","floor":150,"enabled":true},
      {"name":"T1","floor":50,"enabled":true},
      {"name":"T2","floor":30,"enabled":true},
      {"name":"T3","floor":10,"enabled":true},
      {"name":"T4","floor":5,"enabled":true},
      {"name":"T5","floor":1,"enabled":true},
    ],
    wanted: ["Screaming Essence of Fear"], // placeholder, picked at random
    rows: [
      {"name":"Mirror of Kalandra","prices":{"take":369999.4}},
      {"name":"Runegraft of the Warp","prices":{"take":1290.21}},
      {"name":"Tainted Exalted Orb","prices":{"take":486.84}},
      {"name":"Tattoo of the Ramako Shaman","prices":{"take":197.51}},
      {"name":"Message in a Bottle","prices":{"take":152.17}},
      {"name":"Runegraft of Stability","prices":{"take":139.85}},
      {"name":"Fungal Astrolabe","prices":{"take":115.86}},
      {"name":"Omen of Amelioration","prices":{"take":93.97}},
      {"name":"Maven's Chisel of Scarabs","prices":{"take":54.36}},
      {"name":"Tattoo of the Ngamahu Warmonger","prices":{"take":50.19}},
      {"name":"Tattoo of the Ngamahu Firewalker","prices":{"take":48.48}},
      {"name":"Essence of Horror","prices":{"take":44.58}},
      {"name":"Skittering Delirium Orb","prices":{"take":40.6}},
      {"name":"Brinehook's Ducat","prices":{"take":35.48}},
      {"name":"Essence of Insanity","prices":{"take":35.19}},
      {"name":"Maven's Chisel of Divination","prices":{"take":27.67}},
      {"name":"Foulborn Regal Orb","prices":{"take":17.88}},
      {"name":"Fine Delirium Orb","prices":{"take":13.92}},
      {"name":"Tainted Chaos Orb","prices":{"take":12}},
      {"name":"Runegraft of the Combatant","prices":{"take":10}},
      {"name":"Ukatoa's Ducat","prices":{"take":9.98}},
      {"name":"Deafening Essence of Hatred","prices":{"take":8.25}},
      {"name":"Deafening Essence of Woe","prices":{"take":6.74}},
      {"name":"Wailing Essence of Greed","prices":{"take":5.5}},
      {"name":"Weeping Essence of Fear","prices":{"take":5}},
      {"name":"Deafening Essence of Fear","prices":{"take":4.95}},
      {"name":"Foulborn Orb of Augmentation","prices":{"take":3.34}},
      {"name":"Screaming Essence of Doubt","prices":{"take":2.08}},
      {"name":"Screaming Essence of Woe","prices":{"take":1.32}},
      {"name":"Weeping Essence of Woe","prices":{"take":1}},
      {"name":"Screaming Essence of Fear","prices":{"take":0.98}},
      {"name":"Orb of Alchemy","prices":{"take":0.02}},
      {"name":"Whispering Essence of Woe","prices":{}},
    ],
  },
  {
    name: "Map Fragments", key: "MapFragment",
    palette: {"primary":"#b400ff","secondary":"#ffffff","icon":"Star"}, // neversink fragments
    hints: [], // from the taxonomy
    tiers: [
      {"name":"T0","floor":150,"enabled":true},
      {"name":"T1","floor":50,"enabled":true},
      {"name":"T2","floor":30,"enabled":true},
      {"name":"T3","floor":10,"enabled":true},
      {"name":"T4","floor":5,"enabled":true},
      {"name":"T5","floor":1,"enabled":true},
    ],
    wanted: ["Delirium Scarab"], // placeholder, picked at random
    rows: [
      {"name":"Syndicate Medallion","prices":{"take":1644.91}},
      {"name":"Horned Scarab of Preservation","prices":{"take":540.94}},
      {"name":"Echo of Reverence","prices":{"take":316.56}},
      {"name":"Reverent Fragment","prices":{"take":225.07}},
      {"name":"Decaying Fragment","prices":{"take":162.97}},
      {"name":"Legion Scarab of Eternal Conflict","prices":{"take":149.81}},
      {"name":"Fragment of Shape","prices":{"take":124.67}},
      {"name":"Horned Scarab of Awakening","prices":{"take":87.2}},
      {"name":"Trarthan Scarab of Surprising Alliances","prices":{"take":65.71}},
      {"name":"Allflame Ember of Kulemak","prices":{"take":50.42}},
      {"name":"Fragment of Terror","prices":{"take":44.66}},
      {"name":"Ritual Scarab of Abundance","prices":{"take":41.54}},
      {"name":"Sacred Blossom","prices":{"take":37.78}},
      {"name":"Cartography Scarab of Risk","prices":{"take":31.08}},
      {"name":"Horned Scarab of Nemeses","prices":{"take":30.17}},
      {"name":"Bestiary Scarab of Duplicating","prices":{"take":29.26}},
      {"name":"Fragment of Constriction","prices":{"take":18.93}},
      {"name":"Fragment of Purification","prices":{"take":15.88}},
      {"name":"Baran's Crest","prices":{"take":12.1}},
      {"name":"Scarab of Monstrous Lineage","prices":{"take":10.4}},
      {"name":"Hivebrain Gland","prices":{"take":9.99}},
      {"name":"Al-Hezmin's Crest","prices":{"take":7.73}},
      {"name":"Abyss Scarab of Multitudes","prices":{"take":7.3}},
      {"name":"Horned Scarab of Tradition","prices":{"take":5.64}},
      {"name":"Breach Scarab of Instability","prices":{"take":5.22}},
      {"name":"Sacrifice at Noon","prices":{"take":4.57}},
      {"name":"Ritual Scarab of Selectiveness","prices":{"take":2.4}},
      {"name":"Ritual Scarab of Corpses","prices":{"take":1.53}},
      {"name":"Titanic Scarab of Treasures","prices":{"take":1.36}},
      {"name":"Sacrifice at Dawn","prices":{"take":1}},
      {"name":"Delirium Scarab","prices":{"take":0.94}},
      {"name":"Expedition Scarab of Archaeology","prices":{"take":0.68}},
      {"name":"The Black Barya","prices":{}},
    ],
  },
  {
    name: "Skill Gems", key: "skill-gems",
    palette: {"primary":"#14f0f0","secondary":"#460014","icon":"Triangle"}, // neversink exceptional
    hints: [], // from the taxonomy
    tiers: [
      {"name":"T0","floor":150,"enabled":true},
      {"name":"T1","floor":50,"enabled":true},
      {"name":"T2","floor":30,"enabled":true},
      {"name":"T3","floor":10,"enabled":true},
      {"name":"T4","floor":5,"enabled":true},
      {"name":"T5","floor":1,"enabled":true},
    ],
    wanted: ["Cooldown Recovery Support"], // placeholder, picked at random
    rows: [
      {"name":"Awakened Enlighten Support","prices":{"take":40925.55}},
      {"name":"Elemental Penetration Support (21/20 corrupted)","prices":{"check":2116.84}},
      {"name":"Cooldown Recovery Support","prices":{"take":2116.84}},
      {"name":"Melee Physical Damage Support (21/20 corrupted)","prices":{"check":1058.42}},
      {"name":"Guardian's Blessing Support (21/20 corrupted)","prices":{"check":580}},
      {"name":"Lightning Penetration Support (20/23 corrupted)","prices":{"check":352.81}},
      {"name":"Volcanic Fissure of Snaking","prices":{"take":300}},
      {"name":"Elemental Hit of the Spectrum","prices":{"take":230}},
      {"name":"Despair (20/20)","prices":{"take":180}},
      {"name":"Blade Blast (21/20 corrupted)","prices":{"check":160}},
      {"name":"Fortify Support (20/20)","prices":{"take":149}},
      {"name":"Double Strike (Vaal 20/20)","prices":{"check":143}},
      {"name":"Petrified Blood (20/23 corrupted)","prices":{"check":109}},
      {"name":"Slower Projectiles Support (20/20)","prices":{"take":100}},
      {"name":"Cast when Damage Taken Support (20/20)","prices":{"take":80}},
      {"name":"Charged Mines Support (20/23 corrupted)","prices":{"check":80}},
      {"name":"Arcanist Brand (20/23 corrupted)","prices":{"check":64}},
      {"name":"Purity of Lightning (20/20)","prices":{"take":63}},
      {"name":"Winter Orb (20/20)","prices":{"take":50}},
      {"name":"Whirling Blades (20/23 corrupted)","prices":{"check":50}},
      {"name":"Leap Slam (21/20 corrupted)","prices":{"check":49}},
      {"name":"Battlemage's Cry (20/20)","prices":{"take":49}},
      {"name":"Righteous Fire (Vaal 20/20)","prices":{"check":44}},
      {"name":"Summon Phantasm Support (20/20)","prices":{"take":44}},
      {"name":"Withering Touch Support (20/23 corrupted)","prices":{"check":40}},
      {"name":"Anger (20/20)","prices":{"take":39}},
      {"name":"Energy Leech Support (21/20 corrupted)","prices":{"check":32}},
      {"name":"Culling Strike Support (20/20)","prices":{"take":32}},
      {"name":"War Banner (20/23 corrupted)","prices":{"check":30}},
      {"name":"Viper Strike of the Mamba","prices":{"take":30}},
      {"name":"Additional Accuracy Support (21/20 corrupted)","prices":{"check":29}},
      {"name":"Arc of Oscillating","prices":{"take":29}},
      {"name":"Immolate Support (20/23 corrupted)","prices":{"check":20}},
      {"name":"Raise Zombie of Falling","prices":{"take":20}},
      {"name":"Shockwave Totem (21/20 corrupted)","prices":{"check":15}},
      {"name":"Vile Toxins Support (20/20)","prices":{"take":14}},
      {"name":"Damage on Full Life Support (20/23 corrupted)","prices":{"check":10}},
      {"name":"Wither (20/23 corrupted)","prices":{"check":10}},
      {"name":"Flame Link (20/20)","prices":{"take":10}},
      {"name":"Wither (20/20)","prices":{"take":10}},
      {"name":"Alchemist's Mark (20/23 corrupted)","prices":{"check":9}},
      {"name":"Ancestral Call Support (20/20)","prices":{"take":9}},
      {"name":"Hydrosphere (20/23 corrupted)","prices":{"check":8}},
      {"name":"Consecrated Path (20/20)","prices":{"take":7}},
      {"name":"Ambush (21/20 corrupted)","prices":{"check":6}},
      {"name":"Lacerate (20/20)","prices":{"take":6}},
      {"name":"Hexblast (20/23 corrupted)","prices":{"check":5}},
      {"name":"Wild Strike (21/20 corrupted)","prices":{"check":5}},
      {"name":"Fire Trap (20/20)","prices":{"take":5}},
      {"name":"Windburst Support (20/20)","prices":{"take":5}},
      {"name":"Blade Trap of Greatswords","prices":{"take":4}},
      {"name":"Alchemist's Mark (21/20 corrupted)","prices":{"check":4}},
      {"name":"Cold Snap (Vaal 1/0)","prices":{"check":3}},
      {"name":"Blade Trap (21/20 corrupted)","prices":{"check":2}},
      {"name":"Scourge Arrow (21/20 corrupted)","prices":{"check":2}},
      {"name":"Bodyswap (1/0)","prices":{"take":1}},
      {"name":"Frost Wall (1/0)","prices":{"take":1}},
      {"name":"Purity of Fire (1/0)","prices":{"take":1}},
      {"name":"Wrath (1/0)","prices":{"take":1}},
      {"name":"Volcanic Fissure (Vaal 1/0)","prices":{"check":1}},
      {"name":"Added Cold Damage Support (20/23 corrupted)","prices":{}},
      {"name":"Discipline (21/20 corrupted)","prices":{}},
      {"name":"Tectonic Slam (20/23 corrupted)","prices":{}},
    ],
  },
  {
    name: "Breach", key: "breach",
    palette: {"primary":"#411450","secondary":"#ffffff","icon":"Kite"}, // neversink splinter
    hints: [], // from the taxonomy
    tiers: [
      {"name":"T0","floor":150,"enabled":true},
      {"name":"T1","floor":50,"enabled":true},
      {"name":"T2","floor":30,"enabled":true},
      {"name":"T3","floor":10,"enabled":true},
      {"name":"T4","floor":5,"enabled":true},
      {"name":"T5","floor":1,"enabled":true},
    ],
    wanted: ["Ancient Wombgift"], // placeholder, picked at random
    rows: [
      {"name":"Ancient Wombgift","prices":{"take":20}},
      {"name":"Lavish Wombgift","prices":{"take":7}},
      {"name":"Mysterious Wombgift","prices":{"take":2}},
      {"name":"Provisioning Wombgift","prices":{"take":1}},
    ],
  },
  {
    name: "Bases", key: "bases",
    palette: {"primary":"#00f0be","secondary":"#004b1e","icon":"Diamond"}, // neversink expensive
    hints: [], // from the taxonomy
    tiers: [
      {"name":"T0","floor":150,"enabled":true},
      {"name":"T1","floor":50,"enabled":true},
      {"name":"T2","floor":30,"enabled":true},
      {"name":"T3","floor":10,"enabled":true},
      {"name":"T4","floor":5,"enabled":true},
      {"name":"T5","floor":1,"enabled":true},
    ],
    wanted: ["Heavy Arrow Quiver (ilvl 85)"], // placeholder, picked at random
    rows: [
      {"name":"Focused Amulet (ilvl 86 hunter)","prices":{"take":70561.3}},
      {"name":"Warlock Boots (ilvl 86 hunter)","prices":{"take":1058.42}},
      {"name":"Geodesic Ring (ilvl 86 crusader)","prices":{"take":352.81}},
      {"name":"Lich's Circlet (ilvl 85 warlord)","prices":{"take":300}},
      {"name":"Warlock Boots (ilvl 86 warlord)","prices":{"take":150}},
      {"name":"Apothecary's Gloves (ilvl 86 warlord)","prices":{"take":149}},
      {"name":"Warlock Gloves (ilvl 84 warlord)","prices":{"take":100}},
      {"name":"Leviathan Gauntlets (ilvl 84 warlord)","prices":{"take":70}},
      {"name":"Coral Ring (ilvl 84 warlord)","prices":{"take":50}},
      {"name":"Zealot Boots (ilvl 86 redeemer)","prices":{"take":50}},
      {"name":"Blasting Wand (ilvl 85 elder)","prices":{"take":49}},
      {"name":"Primordial Staff (ilvl 83 elder)","prices":{"take":40}},
      {"name":"Two-Toned Boots (ilvl 84 redeemer)","prices":{"take":35}},
      {"name":"Imperial Bow (ilvl 86)","prices":{"take":30}},
      {"name":"Wraith Axe (ilvl 83 warlord)","prices":{"take":30}},
      {"name":"Antique Greaves (ilvl 86 elder)","prices":{"take":29}},
      {"name":"Scholar Boots (ilvl 85 hunter)","prices":{"take":20}},
      {"name":"Behemoth Mace (ilvl 83 shaper)","prices":{"take":14}},
      {"name":"Gripped Gloves (ilvl 86 redeemer)","prices":{"take":10}},
      {"name":"Zealot Helmet (ilvl 84 elder)","prices":{"take":10}},
      {"name":"Abyssal Sceptre (ilvl 86 crusader)","prices":{"take":9}},
      {"name":"Martyr Boots (ilvl 85 warlord)","prices":{"take":7}},
      {"name":"Diamond Ring (ilvl 86 redeemer)","prices":{"take":5}},
      {"name":"Penetrating Arrow Quiver (ilvl 85 hunter)","prices":{"take":5}},
      {"name":"Zodiac Leather (ilvl 86 redeemer)","prices":{"take":5}},
      {"name":"Abyssal Axe (ilvl 86 hunter)","prices":{"take":4}},
      {"name":"Vaal Claw (ilvl 85 hunter)","prices":{"take":3}},
      {"name":"Butcher Axe (ilvl 85 hunter)","prices":{"take":1}},
      {"name":"Moonlit Circlet (ilvl 85 redeemer)","prices":{"take":1}},
      {"name":"Zodiac Leather (ilvl 85 shaper)","prices":{"take":1}},
      {"name":"Heavy Arrow Quiver (ilvl 85)","prices":{"take":0.99}},
      {"name":"Laminated Kite Shield (ilvl 83 warlord)","prices":{}},
      {"name":"Zodiac Leather (ilvl 84 warlord)","prices":{}},
    ],
  },
  {
    name: "Jewels", key: "jewels",
    palette: {"primary":"#9600ff","secondary":"#ffffff","icon":"Pentagon"}, // neversink clustereco
    hints: [], // from the taxonomy
    tiers: [
      {"name":"T0","floor":150,"enabled":true},
      {"name":"T1","floor":50,"enabled":true},
      {"name":"T2","floor":30,"enabled":true},
      {"name":"T3","floor":10,"enabled":true},
      {"name":"T4","floor":5,"enabled":true},
      {"name":"T5","floor":1,"enabled":true},
    ],
    wanted: ["Medium Cluster Jewel - Critical Chance - 6 passives (ilvl 68)"], // placeholder, picked at random
    rows: [
      {"name":"Small Cluster Jewel - Reservation Efficiency - 3 passives (ilvl 84)","prices":{"take":1411.23}},
      {"name":"Large Cluster Jewel - Attack Damage while Dual Wielding - 8 passives (ilvl 50)","prices":{"take":352.81}},
      {"name":"Small Cluster Jewel - Reservation Efficiency - 3 passives (ilvl 50)","prices":{"take":325}},
      {"name":"Large Cluster Jewel - Lightning Damage - 8 passives (ilvl 1)","prices":{"take":246}},
      {"name":"Large Cluster Jewel - Bow Damage - 8 passives (ilvl 50)","prices":{"take":175}},
      {"name":"Large Cluster Jewel - Chaos Damage - 8 passives (ilvl 1)","prices":{"take":100}},
      {"name":"Large Cluster Jewel - Wand Damage - 8 passives (ilvl 50)","prices":{"take":99}},
      {"name":"Large Cluster Jewel - Fire Damage - 8 passives (ilvl 68)","prices":{"take":89}},
      {"name":"Timeless Jewel","prices":{"take":60}},
      {"name":"Medium Cluster Jewel - Flask Duration - 4 passives (ilvl 50)","prices":{"take":50}},
      {"name":"Large Cluster Jewel - Attack Damage while holding a Shield - 8 passives (ilvl 84)","prices":{"take":42}},
      {"name":"Medium Cluster Jewel - Projectile Damage - 4 passives (ilvl 84)","prices":{"take":40}},
      {"name":"Large Cluster Jewel - Cold Damage - 8 passives (ilvl 1)","prices":{"take":30}},
      {"name":"Large Cluster Jewel - Spell Damage - 8 passives (ilvl 84)","prices":{"take":30}},
      {"name":"Prismatic Jewel (ilvl 85)","prices":{"take":30}},
      {"name":"Large Cluster Jewel - Attack Damage while holding a Shield - 8 passives (ilvl 75)","prices":{"take":25}},
      {"name":"Medium Cluster Jewel - Damage while you have a Herald - 5 passives (ilvl 68)","prices":{"take":20}},
      {"name":"Small Cluster Jewel - Reservation Efficiency - 3 passives (ilvl 68)","prices":{"take":15}},
      {"name":"Large Cluster Jewel - Minion Damage - 8 passives (ilvl 75)","prices":{"take":10}},
      {"name":"Small Cluster Jewel - Reservation Efficiency - 2 passives (ilvl 50)","prices":{"take":10}},
      {"name":"Large Cluster Jewel - Attack Damage while Dual Wielding - 8 passives (ilvl 84)","prices":{"take":9}},
      {"name":"Medium Cluster Jewel - Totem Damage - 4 passives (ilvl 84)","prices":{"take":8}},
      {"name":"Large Cluster Jewel - Physical Damage - 8 passives (ilvl 68)","prices":{"take":5}},
      {"name":"Medium Cluster Jewel - Exerted Attack Damage - 6 passives (ilvl 84)","prices":{"take":5}},
      {"name":"Small Cluster Jewel - Reservation Efficiency - 3 passives (ilvl 75)","prices":{"take":5}},
      {"name":"Large Cluster Jewel - Physical Damage - 8 passives (ilvl 75)","prices":{"take":4}},
      {"name":"Large Cluster Jewel - Bow Damage - 12 passives (ilvl 1)","prices":{"take":1}},
      {"name":"Medium Cluster Jewel - Cold Damage over Time - 6 passives (ilvl 75)","prices":{"take":1}},
      {"name":"Medium Cluster Jewel - Totem Damage - 5 passives (ilvl 75)","prices":{"take":1}},
      {"name":"Viridian Jewel (ilvl 86)","prices":{"take":1}},
      {"name":"Medium Cluster Jewel - Critical Chance - 6 passives (ilvl 68)","prices":{"take":0.56}},
      {"name":"Large Cluster Jewel - Mace and Staff Damage - 8 passives (ilvl 84)","prices":{}},
      {"name":"Small Cluster Jewel - Strength - 3 passives (ilvl 84)","prices":{}},
    ],
  },
  {
    name: "Gold", key: "Gold",
    palette: {"primary":"#ebc86e","secondary":"#141400","icon":"Cross"}, // neversink gold
    hints: [], // from the taxonomy
    tiers: [
      {"name":"T0","floor":150,"enabled":true},
      {"name":"T1","floor":50,"enabled":true},
      {"name":"T2","floor":30,"enabled":true},
      {"name":"T3","floor":10,"enabled":true},
      {"name":"T4","floor":5,"enabled":true},
      {"name":"T5","floor":1,"enabled":true},
    ],
    wanted: ["Gold"], // placeholder, picked at random
    rows: [
      {"name":"Gold","prices":{}},
    ],
  },
  {
    name: "Legion", key: "legion",
    palette: {"primary":"#ff00ff","secondary":"#640064","icon":"Circle"}, // guess: neversink miscmapitems
    hints: [], // from the taxonomy
    tiers: [
      {"name":"T0","floor":150,"enabled":true},
      {"name":"T1","floor":50,"enabled":true},
      {"name":"T2","floor":30,"enabled":true},
      {"name":"T3","floor":10,"enabled":true},
      {"name":"T4","floor":5,"enabled":true},
      {"name":"T5","floor":1,"enabled":true},
    ],
    wanted: ["Timeless Maraketh Splinter"], // placeholder, picked at random
    rows: [
      {"name":"Maraketh Enshrouding Crystal","prices":{"take":906.56}},
      {"name":"Timeless Maraketh Emblem","prices":{"take":62.32}},
      {"name":"Timeless Templar Emblem","prices":{"take":34.7}},
      {"name":"Vaal Enshrouding Crystal","prices":{"take":24.83}},
      {"name":"Karui Enshrouding Crystal","prices":{"take":23.57}},
      {"name":"Imperial Enshrouding Crystal","prices":{"take":15.01}},
      {"name":"Templar Enshrouding Crystal","prices":{"take":10.98}},
      {"name":"Timeless Vaal Emblem","prices":{"take":10.02}},
      {"name":"Timeless Karui Emblem","prices":{"take":5.27}},
      {"name":"Timeless Eternal Emblem","prices":{"take":3.37}},
      {"name":"Timeless Templar Splinter","prices":{"take":1.96}},
      {"name":"Timeless Vaal Splinter","prices":{"take":0.56}},
      {"name":"Timeless Maraketh Splinter","prices":{"take":0.11}},
      {"name":"Timeless Eternal Empire Splinter","prices":{}},
    ],
  },
  {
    name: "Delve", key: "delve",
    palette: {"primary":"#ff0000","secondary":"#ffffff","icon":"Star"}, // neversink fossil
    hints: [], // from the taxonomy
    tiers: [
      {"name":"T0","floor":150,"enabled":true},
      {"name":"T1","floor":50,"enabled":true},
      {"name":"T2","floor":30,"enabled":true},
      {"name":"T3","floor":10,"enabled":true},
      {"name":"T4","floor":5,"enabled":true},
      {"name":"T5","floor":1,"enabled":true},
    ],
    wanted: ["Powerful Chaotic Resonator"], // placeholder, picked at random
    rows: [
      {"name":"Hollow Fossil","prices":{"take":355.72}},
      {"name":"Prime Chaotic Resonator","prices":{"take":261.17}},
      {"name":"Faceted Fossil","prices":{"take":198.49}},
      {"name":"Fractured Fossil","prices":{"take":74.49}},
      {"name":"Gilded Fossil","prices":{"take":65.35}},
      {"name":"Sanctified Fossil","prices":{"take":57.41}},
      {"name":"Glyphic Fossil","prices":{"take":49.51}},
      {"name":"Shuddering Fossil","prices":{"take":26.9}},
      {"name":"Dense Fossil","prices":{"take":21.26}},
      {"name":"Deft Fossil","prices":{"take":14.96}},
      {"name":"Jagged Fossil","prices":{"take":12.9}},
      {"name":"Corroded Fossil","prices":{"take":11.53}},
      {"name":"Metallic Fossil","prices":{"take":9.85}},
      {"name":"Serrated Fossil","prices":{"take":9.61}},
      {"name":"Bound Fossil","prices":{"take":8.98}},
      {"name":"Prismatic Fossil","prices":{"take":8.09}},
      {"name":"Tangled Fossil","prices":{"take":5.77}},
      {"name":"Potent Chaotic Resonator","prices":{"take":0.61}},
      {"name":"Powerful Chaotic Resonator","prices":{"take":0.61}},
      {"name":"Primitive Chaotic Resonator","prices":{"take":0.49}},
    ],
  },
  {
    name: "Expedition", key: "expedition",
    palette: {"primary":"#ff5555","secondary":"#28001e","icon":"UpsideDownHouse"}, // neversink logbook
    hints: [], // from the taxonomy
    tiers: [
      {"name":"T0","floor":150,"enabled":true},
      {"name":"T1","floor":50,"enabled":true},
      {"name":"T2","floor":30,"enabled":true},
      {"name":"T3","floor":10,"enabled":true},
      {"name":"T4","floor":5,"enabled":true},
      {"name":"T5","floor":1,"enabled":true},
    ],
    wanted: ["Scrap Metal"], // placeholder, picked at random
    rows: [
      {"name":"Expedition Logbook","prices":{"take":90}},
      {"name":"Exotic Coinage","prices":{"take":3.78}},
      {"name":"Burial Medallion","prices":{"take":1.45}},
      {"name":"Scrap Metal","prices":{"take":0.84}},
      {"name":"Astragali","prices":{"take":0.05}},
    ],
  },
  {
    name: "Heist", key: "heist",
    palette: {"primary":"#4ae63a","secondary":"#141400","icon":"Pentagon"}, // neversink heisttarget
    hints: [], // from the taxonomy
    tiers: [
      {"name":"T0","floor":150,"enabled":true},
      {"name":"T1","floor":50,"enabled":true},
      {"name":"T2","floor":30,"enabled":true},
      {"name":"T3","floor":10,"enabled":true},
      {"name":"T4","floor":5,"enabled":true},
      {"name":"T5","floor":1,"enabled":true},
    ],
    wanted: ["Rogue's Marker"], // placeholder, picked at random
    rows: [
      {"name":"Trarthan Flashpowder (ilvl 84)","prices":{"take":352.81}},
      {"name":"Trarthan Flashpowder (ilvl 83)","prices":{"take":350}},
      {"name":"Simple Lockpick (ilvl 85)","prices":{"take":120}},
      {"name":"Standard Sharpening Stone (ilvl 84)","prices":{"take":86}},
      {"name":"Studded Bracers (ilvl 83)","prices":{"take":80}},
      {"name":"Fine Sensing Charm (ilvl 85)","prices":{"take":60}},
      {"name":"Standard Sharpening Stone (ilvl 83)","prices":{"take":60}},
      {"name":"Rough Sharpening Stone (ilvl 85)","prices":{"take":40}},
      {"name":"Flanged Arrowhead (ilvl 85)","prices":{"take":34}},
      {"name":"Flanged Drill (ilvl 83)","prices":{"take":33}},
      {"name":"Conduit Line (ilvl 84)","prices":{"take":30}},
      {"name":"Hollowpoint Arrowhead (ilvl 85)","prices":{"take":30}},
      {"name":"Thaumaturgical Sensing Charm (ilvl 85)","prices":{"take":28}},
      {"name":"Fine Lockpick (ilvl 85)","prices":{"take":15}},
      {"name":"Rough Sharpening Stone (ilvl 84)","prices":{"take":12}},
      {"name":"Regicide Disguise Kit (ilvl 85)","prices":{"take":10}},
      {"name":"Versatile Keyring (ilvl 84)","prices":{"take":10}},
      {"name":"Burst Band (ilvl 83)","prices":{"take":9}},
      {"name":"Burst Band (ilvl 85)","prices":{"take":8}},
      {"name":"Foliate Brooch (ilvl 84)","prices":{"take":7}},
      {"name":"Golden Brooch (ilvl 83)","prices":{"take":5}},
      {"name":"Winged Sole (ilvl 85)","prices":{"take":5}},
      {"name":"Azurite Flashpowder (ilvl 83)","prices":{"take":4}},
      {"name":"Polished Sensing Charm (ilvl 83)","prices":{"take":3}},
      {"name":"Skeleton Keyring (ilvl 83)","prices":{"take":2}},
      {"name":"Contract: Laboratory","prices":{"take":1}},
      {"name":"Silver Brooch (ilvl 83)","prices":{"take":1}},
      {"name":"Rogue's Marker","prices":{"take":0}},
      {"name":"Golden Slave Idol","prices":{}},
      {"name":"Voltaxic Flashpowder (ilvl 83)","prices":{}},
    ],
  },
  {
    name: "Ritual", key: "ritual",
    palette: {"primary":"#ff0000","secondary":"#ffffff","icon":"Star"}, // neversink corpses
    hints: [], // from the taxonomy
    tiers: [
      {"name":"T0","floor":150,"enabled":true},
      {"name":"T1","floor":50,"enabled":true},
      {"name":"T2","floor":30,"enabled":true},
      {"name":"T3","floor":10,"enabled":true},
      {"name":"T4","floor":5,"enabled":true},
      {"name":"T5","floor":1,"enabled":true},
    ],
    wanted: ["Imperfect Dancing Sword"], // placeholder, picked at random
    rows: [
      {"name":"Perfect Forest Tiger","prices":{"take":24343.65}},
      {"name":"Perfect Guardian Turtle","prices":{"take":1058.42}},
      {"name":"Perfect Warlord","prices":{"take":1058.42}},
      {"name":"Perfect Judgemental Spirit","prices":{"take":230}},
      {"name":"Perfect Spirit of Fortune","prices":{"take":100}},
      {"name":"Perfect Naval Officer","prices":{"take":99}},
      {"name":"Perfect Blood Demon","prices":{"take":80}},
      {"name":"Perfect Hydra","prices":{"take":44}},
      {"name":"Forest Tiger","prices":{"take":35}},
      {"name":"Perfect Pain Artist","prices":{"take":30}},
      {"name":"Perfect Forest Warrior","prices":{"take":28}},
      {"name":"Blood-filled Vessel","prices":{"take":15}},
      {"name":"Perfect Hulking Miscreation","prices":{"take":15}},
      {"name":"Perfect Serpent Warrior","prices":{"take":10}},
      {"name":"Warlord","prices":{"take":10}},
      {"name":"Guardian Turtle","prices":{"take":9}},
      {"name":"Judgemental Spirit","prices":{"take":7}},
      {"name":"Perfect Fiery Cannibal","prices":{"take":7}},
      {"name":"Half-remembered Goliath","prices":{"take":5}},
      {"name":"Perfect Primal Demiurge","prices":{"take":5}},
      {"name":"Forest Warrior","prices":{"take":4}},
      {"name":"Imperfect Guardian Turtle","prices":{"take":2}},
      {"name":"Imperfect Dancing Sword","prices":{"take":1}},
      {"name":"Imperfect Serpent Warrior","prices":{"take":1}},
      {"name":"Slashing Horror","prices":{"take":1}},
      {"name":"Adherent of Zarokh","prices":{}},
      {"name":"Perfect Adherent of Zarokh","prices":{}},
      {"name":"Shadow Berserker","prices":{}},
    ],
  },
  {
    name: "Flasks", key: "flask",
    palette: {"primary":"#32c87d","secondary":"#19644b","icon":"Raindrop"}, // neversink utility
    hints: [], // from the taxonomy
    tiers: [
      {"name":"T0","floor":150,"enabled":true},
      {"name":"T1","floor":50,"enabled":true},
      {"name":"T2","floor":30,"enabled":true},
      {"name":"T3","floor":10,"enabled":true},
      {"name":"T4","floor":5,"enabled":true},
      {"name":"T5","floor":1,"enabled":true},
    ],
    wanted: ["Topaz Flask (ilvl 83)"], // placeholder, picked at random
    rows: [
      {"name":"Iron Flask (ilvl 85)","prices":{"take":352.81}},
      {"name":"Iron Flask (ilvl 84)","prices":{"take":100}},
      {"name":"Iron Flask (ilvl 83)","prices":{"take":20}},
      {"name":"Prismatic Tincture","prices":{"take":15}},
      {"name":"Silver Flask (ilvl 86)","prices":{"take":14}},
      {"name":"Silver Flask (ilvl 85)","prices":{"take":14}},
      {"name":"Diamond Flask (ilvl 86)","prices":{"take":10}},
      {"name":"Bismuth Flask (ilvl 86)","prices":{"take":9}},
      {"name":"Hallowed Hybrid Flask (ilvl 86)","prices":{"take":8}},
      {"name":"Divine Life Flask (ilvl 86)","prices":{"take":5}},
      {"name":"Hallowed Life Flask (ilvl 85)","prices":{"take":5}},
      {"name":"Sanctified Life Flask (ilvl 86)","prices":{"take":5}},
      {"name":"Bismuth Flask (ilvl 85)","prices":{"take":4}},
      {"name":"Quartz Flask (ilvl 85)","prices":{"take":2}},
      {"name":"Corundum Flask (ilvl 85)","prices":{"take":1}},
      {"name":"Ruby Flask (ilvl 83)","prices":{"take":1}},
      {"name":"Topaz Flask (ilvl 85)","prices":{"take":1}},
      {"name":"Topaz Flask (ilvl 83)","prices":{"take":0.56}},
      {"name":"Grand Life Flask (ilvl 85)","prices":{}},
      {"name":"Small Mana Flask (ilvl 84)","prices":{}},
    ],
  },
  {
    name: "Maps", key: "maps",
    palette: {"primary":"#64007a","secondary":"#ffffff","icon":"Square"}, // neversink nightmare
    hints: [], // from the taxonomy
    tiers: [
      {"name":"T0","floor":150,"enabled":true},
      {"name":"T1","floor":50,"enabled":true},
      {"name":"T2","floor":30,"enabled":true},
      {"name":"T3","floor":10,"enabled":true},
      {"name":"T4","floor":5,"enabled":true},
      {"name":"T5","floor":1,"enabled":true},
    ],
    wanted: ["Offering to the Goddess"], // placeholder, picked at random
    rows: [
      {"name":"Cosmic Reliquary Key","prices":{"take":9172.97}},
      {"name":"Shiny Reliquary Key","prices":{"take":1411.23}},
      {"name":"Forgotten Reliquary Key","prices":{"take":1058.42}},
      {"name":"Oubliette Reliquary Key","prices":{"take":352.81}},
      {"name":"Incandescent Invitation","prices":{"take":245}},
      {"name":"Gift to the Goddess","prices":{"take":118.08}},
      {"name":"Nightmare Map","prices":{"take":100}},
      {"name":"Vaal Temple Map","prices":{"take":50}},
      {"name":"An Audience With The King","prices":{"take":42.58}},
      {"name":"Dedication to the Goddess","prices":{"take":22.28}},
      {"name":"The Maven's Writ","prices":{"take":17.35}},
      {"name":"Writhing Invitation","prices":{"take":11}},
      {"name":"Tribute to the Goddess","prices":{"take":10.12}},
      {"name":"Originator Maps (plain)","prices":{"take":10}},
      {"name":"Crescent Splinter","prices":{"take":9.62}},
      {"name":"Originator Maps (8 mods)","prices":{"check":8}},
      {"name":"Originator Maps (unidentified)","prices":{"check":8}},
      {"name":"Eight-mod Maps (8 mods)","prices":{"check":3}},
      {"name":"Eight-mod Maps (unidentified)","prices":{"check":3}},
      {"name":"Forbidden Tome","prices":{"take":3}},
      {"name":"Shaper Guardian Map","prices":{"take":1}},
      {"name":"Offering to the Goddess","prices":{"take":0.64}},
      {"name":"Red Maps","prices":{}},
      {"name":"Yellow Maps","prices":{}},
    ],
  },
  {
    name: "Ultimatum", key: "ultimatum",
    palette: {"primary":"#dcdc00","secondary":"#787800","icon":"Hexagon"}, // guess: neversink special
    hints: [], // from the taxonomy
    tiers: [
      {"name":"T0","floor":150,"enabled":true},
      {"name":"T1","floor":50,"enabled":true},
      {"name":"T2","floor":30,"enabled":true},
      {"name":"T3","floor":10,"enabled":true},
      {"name":"T4","floor":5,"enabled":true},
      {"name":"T5","floor":1,"enabled":true},
    ],
    wanted: ["Fertile Catalyst"], // placeholder, picked at random
    rows: [
      {"name":"Prismatic Catalyst","prices":{"take":119.09}},
      {"name":"Fertile Catalyst","prices":{"take":43.09}},
      {"name":"Tainted Catalyst","prices":{"take":13.66}},
      {"name":"Unstable Catalyst","prices":{"take":7.87}},
      {"name":"Tempering Catalyst","prices":{"take":5.19}},
      {"name":"Accelerating Catalyst","prices":{"take":3.47}},
      {"name":"Turbulent Catalyst","prices":{"take":2.6}},
      {"name":"Noxious Catalyst","prices":{"take":2.27}},
      {"name":"Imbued Catalyst","prices":{"take":1.93}},
      {"name":"Abrasive Catalyst","prices":{"take":1.66}},
      {"name":"Inscribed Ultimatum","prices":{}},
    ],
  },
  {
    name: "Sanctum", key: "sanctum",
    palette: {"primary":"#ff5555","secondary":"#28001e","icon":"UpsideDownHouse"}, // neversink sanctum
    hints: [], // from the taxonomy
    tiers: [
      {"name":"T0","floor":150,"enabled":true},
      {"name":"T1","floor":50,"enabled":true},
      {"name":"T2","floor":30,"enabled":true},
      {"name":"T3","floor":10,"enabled":true},
      {"name":"T4","floor":5,"enabled":true},
      {"name":"T5","floor":1,"enabled":true},
    ],
    wanted: ["Urn Relic"], // placeholder, picked at random
    rows: [
      {"name":"Candlestick Relic","prices":{}},
      {"name":"Papyrus Relic","prices":{}},
      {"name":"Urn Relic","prices":{}},
    ],
  },
  {
    name: "Blight", key: "blight",
    palette: {"primary":"#911edc","secondary":"#ebdcf5","icon":"Square"}, // neversink blighted
    hints: [], // from the taxonomy
    tiers: [
      {"name":"T0","floor":150,"enabled":true},
      {"name":"T1","floor":50,"enabled":true},
      {"name":"T2","floor":30,"enabled":true},
      {"name":"T3","floor":10,"enabled":true},
      {"name":"T4","floor":5,"enabled":true},
      {"name":"T5","floor":1,"enabled":true},
    ],
    wanted: ["Teal Oil"], // placeholder, picked at random
    rows: [
      {"name":"Tainted Oil","prices":{"take":1256.69}},
      {"name":"Golden Oil","prices":{"take":338.02}},
      {"name":"Silver Oil","prices":{"take":156.09}},
      {"name":"Prismatic Oil","prices":{"take":83.84}},
      {"name":"Opalescent Oil","prices":{"take":47.2}},
      {"name":"Blight-ravaged Maps","prices":{"take":40}},
      {"name":"Red Blighted Maps (T16)","prices":{"take":39}},
      {"name":"Red Blighted Maps (T15)","prices":{"take":15}},
      {"name":"Black Oil","prices":{"take":13.11}},
      {"name":"Reflective Oil","prices":{"take":12.04}},
      {"name":"Red Blighted Maps (T14)","prices":{"take":10}},
      {"name":"Red Blighted Maps (T13)","prices":{"take":5}},
      {"name":"Crimson Oil","prices":{"take":4.53}},
      {"name":"White Blighted Maps (T3)","prices":{"take":3}},
      {"name":"White Blighted Maps (T4)","prices":{"take":2}},
      {"name":"Yellow Blighted Maps (T8)","prices":{"take":2}},
      {"name":"White Blighted Maps (T2)","prices":{"take":1}},
      {"name":"Azure Oil","prices":{"take":0.86}},
      {"name":"Teal Oil","prices":{"take":0.38}},
      {"name":"Oil Extractor","prices":{}},
    ],
  },
  {
    name: "Divination Cards", key: "divination-cards",
    palette: {"primary":"#0000ff","secondary":"#ffffff","icon":"Star"}, // neversink divination
    hints: [], // from the taxonomy
    tiers: [
      {"name":"T0","floor":150,"enabled":true},
      {"name":"T1","floor":50,"enabled":true},
      {"name":"T2","floor":30,"enabled":true},
      {"name":"T3","floor":10,"enabled":true},
      {"name":"T4","floor":5,"enabled":true},
      {"name":"T5","floor":1,"enabled":true},
    ],
    wanted: ["The Wrath"], // placeholder, picked at random
    rows: [
      {"name":"The Gemcutter","prices":{"take":136778.5}},
      {"name":"Fire Of Unknown Origin","prices":{"take":5981.86}},
      {"name":"The Demon","prices":{"take":1272.16}},
      {"name":"The Doctor","prices":{"take":395.31}},
      {"name":"Temperance","prices":{"take":153.11}},
      {"name":"Monochrome","prices":{"take":138.24}},
      {"name":"The Forbidden Fruit","prices":{"take":86.29}},
      {"name":"The Last One Standing","prices":{"take":71.29}},
      {"name":"Matryoshka","prices":{"take":57.44}},
      {"name":"The Artist","prices":{"take":50}},
      {"name":"The Hook","prices":{"take":48.46}},
      {"name":"The Cursed King","prices":{"take":40.6}},
      {"name":"The Strategist","prices":{"take":35.8}},
      {"name":"Imperfect Memories","prices":{"take":33.31}},
      {"name":"The Hive of Knowledge","prices":{"take":30}},
      {"name":"The Vast","prices":{"take":27.25}},
      {"name":"Anarchy's Price","prices":{"take":20}},
      {"name":"Unchained","prices":{"take":15.6}},
      {"name":"Keeper's Corruption","prices":{"take":11}},
      {"name":"The Shortcut","prices":{"take":10}},
      {"name":"The Enthusiasts","prices":{"take":9.75}},
      {"name":"Rebirth and Renewal","prices":{"take":8}},
      {"name":"The Feast","prices":{"take":7.8}},
      {"name":"Misery in Darkness","prices":{"take":6.5}},
      {"name":"The One That Got Away","prices":{"take":5}},
      {"name":"The Card Sharp","prices":{"take":4.86}},
      {"name":"The Traitor","prices":{"take":3}},
      {"name":"The Skeleton","prices":{"take":2.12}},
      {"name":"The Scout","prices":{"take":1.25}},
      {"name":"Volatile Power","prices":{"take":1}},
      {"name":"The Wrath","prices":{"take":0.99}},
      {"name":"The Cacophony","prices":{}},
      {"name":"Winter's Embrace","prices":{}},
    ],
  },
  {
    name: "Uniques", key: "unique",
    palette: {"primary":"#af6025","secondary":"#ffffff","icon":"Star"}, // you
    hints: ["check","gamble"], // from the taxonomy
    tiers: [
      {"name":"T0","floor":150,"enabled":true},
      {"name":"T1","floor":50,"enabled":true},
      {"name":"T2","floor":30,"enabled":true},
      {"name":"T3","floor":10,"enabled":true},
      {"name":"T4","floor":5,"enabled":true},
      {"name":"T5","floor":1,"enabled":true},
    ],
    wanted: ["Blood Sceptre Uniques (normal)"], // placeholder, picked at random
    rows: [
      {"name":"Amethyst Ring Uniques (corrupted)","prices":{"check":758073.04}},
      {"name":"Large Cluster Jewel Uniques (normal)","prices":{"take":368793.04}},
      {"name":"Great Helmet Uniques (corrupted)","prices":{"check":6006.84}},
      {"name":"Runic Sollerets Uniques (normal)","prices":{"take":3528.06}},
      {"name":"Sapphire Flask Uniques (normal)","prices":{"take":30,"check":730}},
      {"name":"Map Uniques (normal)","prices":{"take":705.61}},
      {"name":"Labrys Uniques (corrupted)","prices":{"check":353.34}},
      {"name":"Runic Crown Uniques (normal)","prices":{"take":352.81}},
      {"name":"Vaal Regalia Uniques (normal)","prices":{"take":1,"check":150}},
      {"name":"Lacewood Spirit Shield Uniques (normal)","prices":{"take":150}},
      {"name":"Bronze Sceptre Uniques (corrupted)","prices":{"check":140}},
      {"name":"Blood Raiment Uniques (normal)","prices":{"take":50,"check":130}},
      {"name":"Faun's Horn Uniques (normal)","prices":{"take":100}},
      {"name":"Agate Amulet Uniques (corrupted)","prices":{"check":90}},
      {"name":"Martyr Gloves Uniques (normal)","prices":{"take":80}},
      {"name":"Dragonscale Boots Uniques (normal)","prices":{"take":1,"check":70}},
      {"name":"Medium Cluster Jewel Uniques (normal)","prices":{"take":60}},
      {"name":"Callous Mask Uniques (corrupted)","prices":{"check":50}},
      {"name":"Vaal Sceptre Uniques (corrupted)","prices":{"check":50}},
      {"name":"Shield Crab Talisman Uniques (normal)","prices":{"take":50}},
      {"name":"Riveted Gloves Uniques (normal)","prices":{"take":48}},
      {"name":"Abyssal Axe Uniques (normal)","prices":{"take":2,"check":45}},
      {"name":"Colossal Tower Shield Uniques (corrupted)","prices":{"check":40}},
      {"name":"Poleaxe Uniques (corrupted)","prices":{"check":40}},
      {"name":"Quarterstaff Uniques (normal)","prices":{"take":40}},
      {"name":"Torturer Garb Uniques (normal)","prices":{"take":40}},
      {"name":"Vaal Sceptre Uniques (normal)","prices":{"take":3,"check":35}},
      {"name":"Ritual Sceptre Uniques (normal)","prices":{"take":32}},
      {"name":"Varnished Coat Uniques (normal)","prices":{"take":10,"check":30}},
      {"name":"Wyrmscale Boots Uniques (normal)","prices":{"take":30}},
      {"name":"Coral Ring Uniques (normal)","prices":{"take":2,"check":29}},
      {"name":"Teak Round Shield Uniques (normal)","prices":{"take":26}},
      {"name":"Legion Sword Uniques (corrupted)","prices":{"check":20}},
      {"name":"Organic Ring Uniques (normal)","prices":{"take":20}},
      {"name":"Steel Circlet Uniques (normal)","prices":{"take":1,"check":15}},
      {"name":"Destiny Leather Uniques (normal)","prices":{"take":15}},
      {"name":"Blue Pearl Amulet Uniques (normal)","prices":{"take":11}},
      {"name":"Golden Plate Uniques (normal)","prices":{"take":2,"check":10}},
      {"name":"War Sword Uniques (normal)","prices":{"take":1,"check":10}},
      {"name":"Vaal Hatchet Uniques (normal)","prices":{"take":10}},
      {"name":"Exquisite Leather Uniques (normal)","prices":{"take":6,"check":9}},
      {"name":"Crude Bow Uniques (normal)","prices":{"take":1,"check":9}},
      {"name":"Ironscale Gauntlets Uniques (normal)","prices":{"take":6}},
      {"name":"Iron Staff Uniques (normal)","prices":{"take":1,"check":6}},
      {"name":"Bronze Sceptre Uniques (normal)","prices":{"take":5}},
      {"name":"Preventative Contract Uniques (normal)","prices":{"take":5}},
      {"name":"Visored Sallet Uniques (normal)","prices":{"take":5}},
      {"name":"Golden Plate Uniques (corrupted)","prices":{"check":5}},
      {"name":"Samite Gloves Uniques (corrupted)","prices":{"check":5}},
      {"name":"Wolf Pelt Uniques (corrupted)","prices":{"check":5}},
      {"name":"Blood Sceptre Uniques (normal)","prices":{"take":4}},
      {"name":"Awl Uniques (corrupted)","prices":{"check":4}},
      {"name":"Painted Buckler Uniques (corrupted)","prices":{"check":4}},
      {"name":"Secutor Helm Uniques (normal)","prices":{"take":2}},
      {"name":"Sabre Uniques (corrupted)","prices":{"check":2}},
      {"name":"Estoc Uniques (normal)","prices":{"take":1}},
      {"name":"Rock Breaker Uniques (normal)","prices":{"take":1}},
      {"name":"Wyrmscale Gauntlets Uniques (normal)","prices":{"take":1}},
      {"name":"Jasper Chopper Uniques (corrupted)","prices":{"check":1}},
      {"name":"Twilight Blade Uniques (corrupted)","prices":{"check":1}},
      {"name":"Ancient Gauntlets Uniques (corrupted)","prices":{}},
      {"name":"Iron Sceptre Uniques","prices":{}},
      {"name":"Wereclaw Talisman Uniques (corrupted)","prices":{}},
    ],
  },
  {
    name: "Foulborn Uniques", key: "foulborn",
    palette: {"primary":"#af6025","secondary":"#ffffff","icon":"Star"}, // neversink foulborn
    hints: ["check","gamble"], // from the taxonomy
    tiers: [
      {"name":"T0","floor":150,"enabled":true},
      {"name":"T1","floor":50,"enabled":true},
      {"name":"T2","floor":30,"enabled":true},
      {"name":"T3","floor":10,"enabled":true},
      {"name":"T4","floor":5,"enabled":true},
      {"name":"T5","floor":1,"enabled":true},
    ],
    wanted: ["Foulborn Widowsilk Robe Uniques (normal)"], // placeholder, picked at random
    rows: [
      {"name":"Foulborn Viridian Jewel Uniques (normal)","prices":{"take":1,"check":1234822.73}},
      {"name":"Foulborn Crimson Jewel Uniques (normal)","prices":{"take":5,"check":68797.27}},
      {"name":"Foulborn Simple Robe Uniques (normal)","prices":{"take":11642.61,"check":19404.36}},
      {"name":"Foulborn Blinder Uniques (normal)","prices":{"take":1,"check":5292.1}},
      {"name":"Foulborn Wyrmscale Doublet Uniques (normal)","prices":{"take":352.81,"check":4233.68}},
      {"name":"Foulborn Rawhide Boots Uniques (normal)","prices":{"take":1764.03}},
      {"name":"Foulborn Reaver Sword Uniques (corrupted)","prices":{"check":1413.37}},
      {"name":"Foulborn Paua Amulet Uniques (normal)","prices":{"take":1058.42}},
      {"name":"Foulborn Eternal Sword Uniques (normal)","prices":{"take":300}},
      {"name":"Foulborn Gavel Uniques (normal)","prices":{"take":30,"check":150}},
      {"name":"Foulborn Amber Amulet Uniques (normal)","prices":{"take":1,"check":140}},
      {"name":"Foulborn Onyx Amulet Uniques (normal)","prices":{"take":1,"check":140}},
      {"name":"Foulborn Two-Stone Ring Uniques (normal)","prices":{"take":3,"check":99}},
      {"name":"Foulborn Silk Gloves Uniques (normal)","prices":{"take":99}},
      {"name":"Foulborn Midnight Blade Uniques (normal)","prices":{"take":2,"check":54}},
      {"name":"Foulborn Necromancer Silks Uniques (normal)","prices":{"take":40,"check":50}},
      {"name":"Foulborn Prismatic Ring Uniques (normal)","prices":{"take":1,"check":45}},
      {"name":"Foulborn Ranger Bow Uniques (normal)","prices":{"take":3,"check":40}},
      {"name":"Foulborn Sorcerer Boots Uniques (normal)","prices":{"take":40}},
      {"name":"Foulborn Agate Amulet Uniques (normal)","prices":{"take":1,"check":30}},
      {"name":"Foulborn Short Bow Uniques (normal)","prices":{"take":3,"check":30}},
      {"name":"Foulborn Zodiac Leather Uniques (normal)","prices":{"take":1,"check":30}},
      {"name":"Foulborn Astral Plate Uniques (normal)","prices":{"take":30}},
      {"name":"Foulborn Murder Mitts Uniques (normal)","prices":{"take":25}},
      {"name":"Foulborn Topaz Ring Uniques (normal)","prices":{"take":5,"check":25}},
      {"name":"Foulborn Tomahawk Uniques (normal)","prices":{"take":20}},
      {"name":"Foulborn Two-Point Arrow Quiver Uniques (normal)","prices":{"take":15}},
      {"name":"Foulborn Titan Greaves Uniques (normal)","prices":{"take":1,"check":15}},
      {"name":"Foulborn Exquisite Leather Uniques (normal)","prices":{"take":10}},
      {"name":"Foulborn Studded Belt Uniques (normal)","prices":{"take":10}},
      {"name":"Foulborn Labrys Uniques (normal)","prices":{"take":2,"check":10}},
      {"name":"Foulborn Sadist Garb Uniques (normal)","prices":{"take":2,"check":10}},
      {"name":"Foulborn Vaal Sceptre Uniques (normal)","prices":{"take":3,"check":10}},
      {"name":"Foulborn Assassin Bow Uniques (normal)","prices":{"take":1,"check":9}},
      {"name":"Foulborn Deerskin Gloves Uniques (normal)","prices":{"take":5,"check":9}},
      {"name":"Foulborn Cutlass Uniques (normal)","prices":{"take":2,"check":7}},
      {"name":"Foulborn Devout Chainmail Uniques (normal)","prices":{"take":7}},
      {"name":"Foulborn Calling Wand Uniques (normal)","prices":{"take":3,"check":5}},
      {"name":"Foulborn Sinner Tricorne Uniques (normal)","prices":{"take":4,"check":5}},
      {"name":"Foulborn Varnished Coat Uniques (normal)","prices":{"take":2,"check":5}},
      {"name":"Foulborn Engraved Wand Uniques (normal)","prices":{"take":5}},
      {"name":"Foulborn Imbued Wand Uniques (normal)","prices":{"take":5}},
      {"name":"Foulborn Majestic Plate Uniques (normal)","prices":{"take":5}},
      {"name":"Foulborn Chain Belt Uniques (normal)","prices":{"take":2,"check":4}},
      {"name":"Foulborn Widowsilk Robe Uniques (normal)","prices":{"take":3}},
      {"name":"Foulborn Titan Gauntlets Uniques (normal)","prices":{"take":1,"check":2}},
      {"name":"Foulborn Gilded Sallet Uniques (normal)","prices":{"take":1}},
      {"name":"Foulborn Wyrmscale Gauntlets Uniques (normal)","prices":{"take":1}},
      {"name":"Foulborn Abyssal Axe Uniques (corrupted)","prices":{}},
      {"name":"Foulborn Lion Sword Uniques (corrupted)","prices":{}},
      {"name":"Foulborn Zodiac Leather Uniques (corrupted)","prices":{}},
    ],
  },
];
