import { describe, it, expect } from "@jest/globals";
import { evaluateFilter } from "@poe/filter-eval/evaluate-filter";
import { parseFilter } from "@poe/filter-eval/parse-filter";
import { styleFilter } from "./style-filter.ts";

/**
 * A proto filter in, a drawable one out.
 *
 * What is being checked is mostly a negative: styling adds action lines and changes nothing
 * else. So the tests read the output back through the same parser the pipeline uses and
 * compare what the game would match on, rather than comparing text.
 *
 * Fixtures are written out rather than read from `proto.filter`. That file is an untracked
 * artefact of a classifier run against a live market, and a test that moves with the market
 * is a test that says nothing on the day it fails.
 */

const PROTO = [
  "# Proto filter — generated. Every line below came out of a bucket; none was typed.",
  "#",
  "# There are no colours, sounds or font sizes here. This file says what an item is",
  "# worth, not how to draw it.",
  "",
  `# ${"-".repeat(84)}`,
  "# block 1 of 4 — T0 take, stackables",
  "Show",
  '\tBaseType == "Mirror of Kalandra"',
  "\t#@ tier=T0 verb=take family=stackables bucket stack:currency/Mirror of Kalandra",
  "",
  `# ${"-".repeat(84)}`,
  "# block 2 of 4 — T2 check, uniques-by-base",
  "Show",
  "\tRarity Unique",
  '\tBaseType == "Heavy Belt"',
  "\t#@ tier=T2 verb=check family=uniques-by-base bucket unique:Heavy Belt",
  "",
  `# ${"-".repeat(84)}`,
  "# block 3 of 4 — T4 gamble, uniques-by-base",
  "Show",
  "\tRarity Unique",
  '\tBaseType == "Moonstone Ring"',
  "\tAreaLevel >= 68 # generated by bucket unique:Moonstone Ring",
  "\t#@ tier=T4 verb=gamble family=uniques-by-base bucket unique:Moonstone Ring",
  "",
  `# ${"-".repeat(84)}`,
  "# block 4 of 4 — hidden take, stackables",
  "Hide",
  '\tBaseType == "Scroll Fragment"',
  "\t#@ tier=hidden verb=take family=stackables bucket stack:currency/Scroll Fragment",
  "",
].join("\n");

/** The action lines of the nth block, without their tab. */
const actionsOf = (text: string, nth: number): string[] => {
  const blocks = text.split(/^(?=Show|Hide|Minimal)/m).slice(1);

  return (blocks[nth] ?? "")
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => /^(Set|Play|Minimap|Enable|Disable)/.test(line));
};

describe("styleFilter", () => {
  it("gives the top currency rung everything buckets.md asks of it", () => {
    // `C:WhiteAndRed`, a large red circle, Whoosh, XL and a permanent red beam — the whole
    // of currency `T0`, in the order the actions are written.
    expect(actionsOf(styleFilter(PROTO), 0)).toEqual([
      "SetFontSize 45",
      "SetTextColor 255 0 0 255",
      "SetBorderColor 255 0 0 255",
      "SetBackgroundColor 255 255 255 255",
      "PlayAlertSound 6 300",
      "EnableDropSound",
      "PlayEffect Red",
      "MinimapIcon 0 Red Circle",
    ]);
  });

  it("keeps the game's own drop noise wherever there is an alert sound", () => {
    const loud = actionsOf(styleFilter(PROTO), 0);
    const silent = actionsOf(styleFilter(PROTO), 2);

    // Every sound in `buckets.md` is written `Sound:n:300:Drop`, so the two travel
    // together — and a block with no alert sound has no drop noise to restore.
    expect(loud).toContain("PlayAlertSound 6 300");
    expect(loud).toContain("EnableDropSound");
    expect(silent.some((line) => line.startsWith("PlayAlertSound"))).toBe(false);
    expect(silent).not.toContain("EnableDropSound");
  });

  it("draws a unique in the unique palette, not the currency one", () => {
    const actions = actionsOf(styleFilter(PROTO), 2);

    // `U:BrownAndBlack:Gamble`: the unique reddish. The family decided which ladder was
    // read, and nothing here is the currency orange. Read off the gamble block rather than
    // the check beside it, because a check repaints every colour it is handed and would
    // say nothing about which palette it came from.
    expect(actions).toContain("SetBackgroundColor 175 60 37 255");
    expect(actions).not.toContain("SetBackgroundColor 240 90 35 255");
  });

  it("marks a check without making it louder", () => {
    const actions = actionsOf(styleFilter(PROTO), 1);

    // **A check is a question, not a louder answer.** The bucket is drawn at what the base
    // is *guaranteed* to be worth, and the marker says only that there may be more here.
    // So it changes the things read once the item is on screen — a gold border, a label big
    // enough to notice, a small yellow star…
    expect(actions).toContain("SetBorderColor 255 190 0 255");
    expect(actions).toContain("SetFontSize 35");
    expect(actions).toContain("MinimapIcon 2 Yellow Star");

    // …tints the background rather than replacing it, so the rung is still legible under
    // the mark. `U:BrownAndBrown` is rgb(53, 13, 13), and a fifth of the way to the gold is
    // this — a suggestion the border carries, not a repaint.
    // The text is then whichever of black and white reads on what came out — no fixed
    // colour survives every rung, which is why nothing configures one.
    expect(actions).toContain("SetBackgroundColor 93 48 10 255");
    expect(actions).toContain("SetTextColor 255 255 255 255");

    // …recolours the beam to match, because a beam is the only mark the game draws in the
    // world and two marks on one item should not disagree about what it is…
    expect(actions).toContain("PlayEffect Yellow");

    // …and never touches the sound, which is the one line that says *stop what you are
    // doing* and is not a maybe's to spend.
    expect(actions).toContain("PlayAlertSound 3 300");

    // …and the sound is the rung's own, which is the one thing left that a check does not
    // repaint. Everything a check touches is colour and size; the noise stays the tier's.
    expect(actions).not.toContain("PlayAlertSound 6 300");
  });

  it("swaps in the gamble template at the rung the bucket already sits on", () => {
    const actions = actionsOf(styleFilter(PROTO), 2);

    // `U:BrownAndBlack:Gamble` — the reddish background that means *this is not what it
    // says it is*, over T4 check's own size. The rung decides how loud, the gamble decides
    // the paint, and neither overrules the other.
    expect(actions).toContain("SetBackgroundColor 175 60 37 255");
    expect(actions).toContain("SetFontSize 26");
    expect(actions.some((line) => line.startsWith("PlayAlertSound"))).toBe(false);
  });

  it("writes no actions on a Hide block", () => {
    expect(actionsOf(styleFilter(PROTO), 3)).toEqual([]);
  });

  it("leaves every block matching exactly what it matched before", () => {
    const shape = (text: string): unknown[] =>
      parseFilter(text).map((block) => [
        block.keyword,
        block.conditions.map((one) => [one.name, one.operator, ...one.values]),
        block.notes.map((note) => `${note.key}=${note.value}`),
      ]);

    const before = shape(PROTO);
    const after = shape(styleFilter(PROTO));

    // Two longer: the hide layer and the catch-all. Everything before them is untouched.
    expect(after).toHaveLength(before.length + 2);
    expect(after.slice(0, before.length)).toEqual(before);
  });

  it("keeps the comment a condition carries its provenance in", () => {
    const [, , third] = parseFilter(styleFilter(PROTO));

    expect(third?.conditions[2]?.comment).toBe(
      "generated by bucket unique:Moonstone Ring",
    );
  });

  it("ends on a catch-all that shows rather than hides", () => {
    const styled = styleFilter(PROTO);
    const last = parseFilter(styled).at(-1);

    expect(last?.keyword).toBe("Show");
    // No conditions at all: that is what makes it the catch-all rather than a block.
    expect(last?.conditions).toEqual([]);
    expect(last?.freehand).toContain("catch-all");
    // `varies`, because nothing tiered it — and magenta, which is what that looks like.
    expect(last?.notes.map((note) => `${note.key}=${note.value}`)).toEqual([
      "tier=varies",
      "verb=check",
    ]);
    expect(actionsOf(styled, 5)).toEqual([
      "SetFontSize 45",
      "SetTextColor 255 0 255 255",
      "SetBorderColor 255 0 255 255",
      "SetBackgroundColor 100 0 100 255",
      "PlayAlertSound 3 300",
      "PlayEffect Pink",
      "MinimapIcon 0 Pink Circle",
    ]);
  });

  it("hides the gear no block claimed, one block above the catch-all", () => {
    const blocks = parseFilter(styleFilter(PROTO));
    const layer = blocks.at(-2);

    expect(layer?.keyword).toBe("Hide");
    expect(layer?.freehand).toContain("hide layer");

    const [only] = layer?.conditions ?? [];
    expect(only?.name).toBe("Class");
    // A bare `Class`, which the grammar reads as a substring match, is NeverSink's spelling
    // and the forgiving direction when GGG renames a class.
    expect(only?.operator).toBe("=");
    expect(only?.values).toContain("Body Armours");
    expect(only?.values).toContain("Rings");
  });

  it("sends a rare body armour to the hide layer, not to the catch-all", () => {
    const blocks = parseFilter(styleFilter(PROTO));

    const result = evaluateFilter(blocks, {
      BaseType: "Vaal Regalia",
      Class: "Body Armours",
      Rarity: "Rare",
      ItemLevel: 84,
      Corrupted: false,
      Identified: false,
      Quality: 0,
    });

    expect(result.verdict).toBe("Hide");
    expect(result.matched.at(-1)?.freehand).toContain("hide layer");
  });

  it("still sends an unknown currency to the catch-all", () => {
    const blocks = parseFilter(styleFilter(PROTO));

    const result = evaluateFilter(blocks, {
      BaseType: "Orb of Whatever Comes Next",
      Class: "Stackable Currency",
      Rarity: "Normal",
      StackSize: 1,
      Corrupted: false,
      Identified: true,
    });

    expect(result.verdict).toBe("Show");
    expect(result.matched.at(-1)?.freehand).toContain("catch-all");
  });

  it("drops the header's promise that the file has no colours in it", () => {
    const styled = styleFilter(PROTO);

    expect(styled).not.toContain("There are no colours");
    expect(styled).toContain("packages/filter/styles.ts");
    expect(styled.startsWith("# Item filter")).toBe(true);
  });

  it("styles a filter with no header at all", () => {
    const bare = [
      "Show",
      '\tBaseType == "Chaos Orb"',
      "\t#@ tier=T4 verb=take family=stackables bucket stack:currency/Chaos Orb",
      "",
    ].join("\n");

    expect(actionsOf(styleFilter(bare), 0)).toContain("SetBackgroundColor 249 150 25 255");
  });
});
